//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Lecturer = new HashSet<Lecturer>();
            this.Student = new HashSet<Student>();
            this.Results = new HashSet<Results>();
        }
    
        public string Login { get; set; }
        public string Password { get; set; }
        public int SecretQuestionId { get; set; }
        public string Answer { get; set; }
    
        public virtual ICollection<Lecturer> Lecturer { get; set; }
        public virtual ICollection<Student> Student { get; set; }
        public virtual Question Question { get; set; }
        public virtual ICollection<Results> Results { get; set; }
    }
}
