//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseMVVM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int QuestionId { get; set; }
        public string SecretQuestion { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
